### PR TITLE
Docs and cleanup

### PR DESCRIPTION
**Pull request by jtc42**
Once this is merged, I'll do a 3.3.1 release so we have a clean, up to date tag, and update the schema links in the sample files.

### CODE REVIEW

**Comment by George-D-S** [comment]
I've taken off the noout as I'd want to know there error.

Then comparing the output we get -

`./sample_files/ukrdc/fullDemographics.xml:14: element NumberType: Schemas validity error : Element 'NumberType': [facet 'enumeration'] The value 'APPLE' is not an element of the set {'MRN', 'NI'}.
./sample_files/ukrdc/fullDemographics.xml fails to validate
Error: Process completed with exit code 3.`

with xmllint and...

` Element 'Organization': [facet 'enumeration'] The value 'BANANA' is not an element of the set {'NHS', 'CHI', 'HSC', 'UKRR', 'SRR', 'NHSBT', 'RADAR', 'BAPN', 'LOCALHOSP', 'UKRR_UID', 'STUDYNO'}.
sample_files/ukrdc/fullDemographics.xml / Line Number: 13 Column Number: 0
/ukrdc:PatientRecord/Patient/PatientNumbers/PatientNumber[2]/Organization
Error:  1
Element 'NumberType': [facet 'enumeration'] The value 'APPLE' is not an element of the set {'MRN', 'NI'}.
sample_files/ukrdc/fullDemographics.xml / Line Number: 14 Column Number: 0
/ukrdc:PatientRecord/Patient/PatientNumbers/PatientNumber[2]/NumberType`

With PyTest.

There may be parameters to change the xmllint output but by default you get more information from the script.

Is there any harm in just leaving both enabled for now?

**Comment by jtc42** [comment]
> I've taken off the noout as I'd want to know the error.
> 
> Then comparing the output we get -
> 
> ```
> ./sample_files/ukrdc/fullDemographics.xml:14: element NumberType: Schemas validity error : Element 'NumberType': [facet 'enumeration'] The value 'APPLE' is not an element of the set {'MRN', 'NI'}.
> ./sample_files/ukrdc/fullDemographics.xml fails to validate
> Error: Process completed with exit code 3.
> ```
> 
> with xmllint and...
> 
> ```
> Element 'Organization': [facet 'enumeration'] The value 'BANANA' is not an element of the set {'NHS', 'CHI', 'HSC', 'UKRR', 'SRR', 'NHSBT', 'RADAR', 'BAPN', 'LOCALHOSP', 'UKRR_UID', 'STUDYNO'}.
> sample_files/ukrdc/fullDemographics.xml / Line Number: 13 Column Number: 0
> /ukrdc:PatientRecord/Patient/PatientNumbers/PatientNumber[2]/Organization
> 
> Error:  1
> Element 'NumberType': [facet 'enumeration'] The value 'APPLE' is not an element of the set {'MRN', 'NI'}.
> sample_files/ukrdc/fullDemographics.xml / Line Number: 14 Column Number: 0
> /ukrdc:PatientRecord/Patient/PatientNumbers/PatientNumber[2]/NumberType
> ```
> 
> With PyTest.
> 
> There may be parameters to change the xmllint output but by default you get more information from the script.
> 
> Is there any harm in just leaving both enabled for now?

Nope, to be honest when I added xmllint I hadn't appreciated that the pytest tests were actually testing the samples for validation. 

I think that's just me forgetting though! I'll just remove the xmllint job since it seems pointless.

**Comment by George-D-S** [comment]
I've added back outputting the XPath of the erroring element.

Everything else seems fine.

**Review by George-D-S — APPROVED** [review]

**Comment by jtc42** [comment]
> I've added back outputting the XPath of the erroring element.
> 
> 
> 
> Everything else seems fine.

Whoops thanks for spotting that!

**Pull request merged**
